#pragma once

#define CAE_PARSER_VERSION_MAJOR 0
#define CAE_PARSER_VERSION_MINOR 0
#define CAE_PARSER_VERSION_PATCH 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define CAE_PARSER_VERSION_STRING    \
  TOSTRING(CAE_PARSER_VERSION_MAJOR) \
  "." TOSTRING(CAE_PARSER_VERSION_MINOR) "." TOSTRING(CAE_PARSER_VERSION_PATCH)
